set_property PACKAGE_PIN AT11 [ get_ports "W_LED_2" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "W_LED_2" ]

set_property PACKAGE_PIN AU10 [ get_ports "W_LED_3" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "W_LED_3" ]

set_property PACKAGE_PIN AM8 [ get_ports "R_LED_0" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "R_LED_0" ]

set_property PACKAGE_PIN AM7 [ get_ports "G_LED_0" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "G_LED_0" ]

set_property PACKAGE_PIN AN8 [ get_ports "B_LED_0" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "B_LED_0" ]

set_property PACKAGE_PIN AR12 [ get_ports "R_LED_1" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "R_LED_1" ]

set_property PACKAGE_PIN AP8 [ get_ports "G_LED_1" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "G_LED_1" ]

set_property PACKAGE_PIN AT10 [ get_ports "B_LED_1" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "B_LED_1" ]


## USER PUSH BUTTON
set_property PACKAGE_PIN AV12 [ get_ports "PB_0" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "PB_0" ]

set_property PACKAGE_PIN AV10 [ get_ports "PB_1" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "PB_1" ]

set_property PACKAGE_PIN AW9 [ get_ports "PB_2" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "PB_2" ]

set_property PACKAGE_PIN AT12 [ get_ports "PB_3" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "PB_3" ]

set_property PACKAGE_PIN AN12 [ get_ports "PB_4" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "PB_4" ]

## USER SLIDE SWITCH
set_property PACKAGE_PIN AN13 [ get_ports "SW_0" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "SW_0" ]

set_property PACKAGE_PIN AU12 [ get_ports "SW_1" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "SW_1" ]

set_property PACKAGE_PIN AW11 [ get_ports "SW_2" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "SW_2" ]

set_property PACKAGE_PIN AV11 [ get_ports "SW_3" ]
set_property IOSTANDARD LVCMOS18 [ get_ports "SW_3" ]





# LMK 4828 reset
#set_property PACKAGE_PIN T26 [get_ports "lmk_rst[0]"]
set_property PACKAGE_PIN AT9 [get_ports "lmk_rst[0]"]
set_property IOSTANDARD LVCMOS18 [get_ports "lmk_rst[0]"]
# LVCMOS18 is not right, should be 3.3

# DDR4 Led
set_property PACKAGE_PIN AR11 [get_ports "ddr4_led"]
set_property IOSTANDARD LVCMOS18 [get_ports "ddr4_led"]

set_property PACKAGE_PIN AW10 [get_ports "gpio_test"]
set_property IOSTANDARD LVCMOS18 [get_ports "gpio_test"]

# LMK4828 clocks
# AN11 - FPGA_REFCLK_IN_P - LMK CLK 1 - 122.88 MHz
# AP18 - SYSREF_FPGA_P    - LMK CLK 2 -   7.68 MHz

set_property PACKAGE_PIN AN11 [get_ports "lmk_clk1_clk_p"]
set_property PACKAGE_PIN AP11 [get_ports "lmk_clk1_clk_n"]
set_property IOSTANDARD LVDS [get_ports "lmk_clk1_clk_p"]
set_property PACKAGE_PIN AP18 [get_ports "lmk_clk2_clk_p"]
set_property PACKAGE_PIN AR18 [get_ports "lmk_clk2_clk_n"]
set_property IOSTANDARD LVDS [get_ports "lmk_clk2_clk_p"]

create_clock -period 8.13802083 -name lmk_clk1_clk [get_ports "lmk_clk1_clk_p"]
create_clock -period 130.208333 -name lmk_clk2_clk [get_ports "lmk_clk2_clk_p"]
#set_input_delay -clock [get_clocks lmk_clk2_clk] -min -add_delay 1.447 [get_ports "lmk_clk1_clk_p"]
#set_input_delay -clock [get_clocks lmk_clk2_clk] -max -add_delay 2.447 [get_ports "lmk_clk1_clk_p"]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets system_bd_i/clocktreeMTS/IBUFDS_PL_CLK/U0/USE_IBUFDS.GEN_IBUFDS[0].IBUFDS_I/O]
set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets system_bd_i/clocktreeMTS/BUFG_PL_CLK/U0/BUFG_O[0]]





# USE PL_LEDGRB0_G FOR MIG DDDR4 INTERFACE TESTING 
# NOT REQUIRED IN THE USER DESIGN
set_property PACKAGE_PIN AM7 [get_ports c0_init_calib_complete]
#
# USE PL_LEDGRB1_R FOR MIG DDDR4 INTERFACE TESTING 
# NOT REQUIRED IN THE USER DESIGN
set_property PACKAGE_PIN AR12 [get_ports c0_data_compare_error]
#
# USE PL_PB0 FOR MIG DDDR4 INTERFACE TESTING 
# NOT REQUIRED IN THE USER DESIGN
set_property PACKAGE_PIN AV12 [get_ports c0_sys_rst]

set_property IOSTANDARD LVCMOS18 [get_ports c0_init_calib_complete]
set_property DRIVE 8 [get_ports c0_init_calib_complete]
set_property IOSTANDARD LVCMOS18 [get_ports c0_data_compare_error]
set_property DRIVE 8 [get_ports c0_data_compare_error]
set_property IOSTANDARD LVCMOS18 [get_ports c0_sys_rst]






# PL DDR4
# IO constraints for the PL_DDR4 INTERFACE ON THE RFSoC 4x2 board
# DO NOT MODIFY ANY OF THE IO CHARACTERISTICS AS THEY HAVE BEEN TUNED # FOR MAXIMUM PERFORMANCE

set_property PACKAGE_PIN J15 [get_ports {ddr4_pl_dm_n[0]}]
set_property PACKAGE_PIN N14 [get_ports {ddr4_pl_dm_n[1]}]
set_property PACKAGE_PIN D18 [get_ports {ddr4_pl_dm_n[2]}]
set_property PACKAGE_PIN G17 [get_ports {ddr4_pl_dm_n[3]}]
set_property PACKAGE_PIN F21 [get_ports {ddr4_pl_dm_n[4]}]
set_property PACKAGE_PIN J23 [get_ports {ddr4_pl_dm_n[5]}]
set_property PACKAGE_PIN C23 [get_ports {ddr4_pl_dm_n[6]}]
set_property PACKAGE_PIN N20 [get_ports {ddr4_pl_dm_n[7]}]
set_property PACKAGE_PIN L19 [get_ports {ddr4_pl_dq[63]}]
set_property PACKAGE_PIN L23 [get_ports {ddr4_pl_dq[62]}]
set_property PACKAGE_PIN M19 [get_ports {ddr4_pl_dq[61]}]
set_property PACKAGE_PIN N19 [get_ports {ddr4_pl_dq[60]}]
set_property PACKAGE_PIN L21 [get_ports {ddr4_pl_dq[59]}]
set_property PACKAGE_PIN L22 [get_ports {ddr4_pl_dq[58]}]
set_property PACKAGE_PIN L20 [get_ports {ddr4_pl_dq[57]}]
set_property PACKAGE_PIN M20 [get_ports {ddr4_pl_dq[56]}]
set_property PACKAGE_PIN B20 [get_ports {ddr4_pl_dq[55]}]
set_property PACKAGE_PIN C20 [get_ports {ddr4_pl_dq[54]}]
set_property PACKAGE_PIN A21 [get_ports {ddr4_pl_dq[53]}]
set_property PACKAGE_PIN C22 [get_ports {ddr4_pl_dq[52]}]
set_property PACKAGE_PIN A20 [get_ports {ddr4_pl_dq[51]}]
set_property PACKAGE_PIN B24 [get_ports {ddr4_pl_dq[50]}]
set_property PACKAGE_PIN A24 [get_ports {ddr4_pl_dq[49]}]
set_property PACKAGE_PIN C21 [get_ports {ddr4_pl_dq[48]}]
set_property PACKAGE_PIN H21 [get_ports {ddr4_pl_dq[47]}]
set_property PACKAGE_PIN H23 [get_ports {ddr4_pl_dq[46]}]
set_property PACKAGE_PIN H22 [get_ports {ddr4_pl_dq[45]}]
set_property PACKAGE_PIN L24 [get_ports {ddr4_pl_dq[44]}]
set_property PACKAGE_PIN G23 [get_ports {ddr4_pl_dq[43]}]
set_property PACKAGE_PIN K24 [get_ports {ddr4_pl_dq[42]}]
set_property PACKAGE_PIN G22 [get_ports {ddr4_pl_dq[41]}]
set_property PACKAGE_PIN J21 [get_ports {ddr4_pl_dq[40]}]
set_property PACKAGE_PIN G20 [get_ports {ddr4_pl_dq[39]}]
set_property PACKAGE_PIN F24 [get_ports {ddr4_pl_dq[38]}]
set_property PACKAGE_PIN F20 [get_ports {ddr4_pl_dq[37]}]
set_property PACKAGE_PIN E23 [get_ports {ddr4_pl_dq[36]}]
set_property PACKAGE_PIN E21 [get_ports {ddr4_pl_dq[35]}]
set_property PACKAGE_PIN E22 [get_ports {ddr4_pl_dq[34]}]
set_property PACKAGE_PIN D21 [get_ports {ddr4_pl_dq[33]}]
set_property PACKAGE_PIN E24 [get_ports {ddr4_pl_dq[32]}]
set_property PACKAGE_PIN F15 [get_ports {ddr4_pl_dq[31]}]
set_property PACKAGE_PIN E18 [get_ports {ddr4_pl_dq[30]}]
set_property PACKAGE_PIN E17 [get_ports {ddr4_pl_dq[29]}]
set_property PACKAGE_PIN H18 [get_ports {ddr4_pl_dq[28]}]
set_property PACKAGE_PIN G15 [get_ports {ddr4_pl_dq[27]}]
set_property PACKAGE_PIN F16 [get_ports {ddr4_pl_dq[26]}]
set_property PACKAGE_PIN E16 [get_ports {ddr4_pl_dq[25]}]
set_property PACKAGE_PIN G18 [get_ports {ddr4_pl_dq[24]}]
set_property PACKAGE_PIN A16 [get_ports {ddr4_pl_dq[23]}]
set_property PACKAGE_PIN B19 [get_ports {ddr4_pl_dq[22]}]
set_property PACKAGE_PIN C16 [get_ports {ddr4_pl_dq[21]}]
set_property PACKAGE_PIN D15 [get_ports {ddr4_pl_dq[20]}]
set_property PACKAGE_PIN A19 [get_ports {ddr4_pl_dq[19]}]
set_property PACKAGE_PIN C17 [get_ports {ddr4_pl_dq[18]}]
set_property PACKAGE_PIN A17 [get_ports {ddr4_pl_dq[17]}]
set_property PACKAGE_PIN D16 [get_ports {ddr4_pl_dq[16]}]
set_property PACKAGE_PIN M12 [get_ports {ddr4_pl_dq[15]}]
set_property PACKAGE_PIN M15 [get_ports {ddr4_pl_dq[14]}]
set_property PACKAGE_PIN M13 [get_ports {ddr4_pl_dq[13]}]
set_property PACKAGE_PIN M17 [get_ports {ddr4_pl_dq[12]}]
set_property PACKAGE_PIN L12 [get_ports {ddr4_pl_dq[11]}]
set_property PACKAGE_PIN N15 [get_ports {ddr4_pl_dq[10]}]
set_property PACKAGE_PIN N13 [get_ports {ddr4_pl_dq[9]}]
set_property PACKAGE_PIN N17 [get_ports {ddr4_pl_dq[8]}]
set_property PACKAGE_PIN L17 [get_ports {ddr4_pl_dq[7]}]
set_property PACKAGE_PIN J19 [get_ports {ddr4_pl_dq[6]}]
set_property PACKAGE_PIN K16 [get_ports {ddr4_pl_dq[5]}]
set_property PACKAGE_PIN J18 [get_ports {ddr4_pl_dq[4]}]
set_property PACKAGE_PIN H16 [get_ports {ddr4_pl_dq[3]}]
set_property PACKAGE_PIN H17 [get_ports {ddr4_pl_dq[2]}]
set_property PACKAGE_PIN J16 [get_ports {ddr4_pl_dq[1]}]
set_property PACKAGE_PIN K17 [get_ports {ddr4_pl_dq[0]}]
set_property PACKAGE_PIN K19 [get_ports {ddr4_pl_dqs_t[0]}]
set_property PACKAGE_PIN K18 [get_ports {ddr4_pl_dqs_c[0]}]
set_property PACKAGE_PIN L15 [get_ports {ddr4_pl_dqs_t[1]}]
set_property PACKAGE_PIN L14 [get_ports {ddr4_pl_dqs_c[1]}]
set_property PACKAGE_PIN B18 [get_ports {ddr4_pl_dqs_t[2]}]
set_property PACKAGE_PIN B17 [get_ports {ddr4_pl_dqs_c[2]}]
set_property PACKAGE_PIN G19 [get_ports {ddr4_pl_dqs_t[3]}]
set_property PACKAGE_PIN F19 [get_ports {ddr4_pl_dqs_c[3]}]
set_property PACKAGE_PIN D23 [get_ports {ddr4_pl_dqs_t[4]}]
set_property PACKAGE_PIN D24 [get_ports {ddr4_pl_dqs_c[4]}]
set_property PACKAGE_PIN J20 [get_ports {ddr4_pl_dqs_t[5]}]
set_property PACKAGE_PIN H20 [get_ports {ddr4_pl_dqs_c[5]}]
set_property PACKAGE_PIN B22 [get_ports {ddr4_pl_dqs_t[6]}]
set_property PACKAGE_PIN A22 [get_ports {ddr4_pl_dqs_c[6]}]
set_property PACKAGE_PIN K21 [get_ports {ddr4_pl_dqs_t[7]}]
set_property PACKAGE_PIN K22 [get_ports {ddr4_pl_dqs_c[7]}]
set_property PACKAGE_PIN E13 [get_ports {ddr4_pl_adr[16]}]
set_property PACKAGE_PIN F14 [get_ports {ddr4_pl_adr[15]}]
set_property PACKAGE_PIN K13 [get_ports {ddr4_pl_adr[14]}]
set_property PACKAGE_PIN H11 [get_ports {ddr4_pl_adr[13]}]
set_property PACKAGE_PIN D13 [get_ports {ddr4_pl_adr[12]}]
set_property PACKAGE_PIN G7 [get_ports {ddr4_pl_adr[11]}]
set_property PACKAGE_PIN C15 [get_ports {ddr4_pl_adr[10]}]
set_property PACKAGE_PIN H6 [get_ports {ddr4_pl_adr[9]}]
set_property PACKAGE_PIN A11 [get_ports {ddr4_pl_adr[8]}]
set_property PACKAGE_PIN H13 [get_ports {ddr4_pl_adr[7]}]
set_property PACKAGE_PIN J7 [get_ports {ddr4_pl_adr[6]}]
set_property PACKAGE_PIN F11 [get_ports {ddr4_pl_adr[5]}]
set_property PACKAGE_PIN D14 [get_ports {ddr4_pl_adr[4]}]
set_property PACKAGE_PIN F10 [get_ports {ddr4_pl_adr[3]}]
set_property PACKAGE_PIN A14 [get_ports {ddr4_pl_adr[2]}]
set_property PACKAGE_PIN G6 [get_ports {ddr4_pl_adr[1]}]
set_property PACKAGE_PIN B13 [get_ports {ddr4_pl_adr[0]}]
set_property PACKAGE_PIN A12 [get_ports {ddr4_pl_ba[0]}]
set_property PACKAGE_PIN H10 [get_ports {ddr4_pl_ba[1]}]
set_property PACKAGE_PIN H12 [get_ports {ddr4_pl_bg[0]}]
set_property PACKAGE_PIN E11 [get_ports {ddr4_pl_cs_n[0]}]
set_property PACKAGE_PIN B14 [get_ports ddr4_pl_act_n]
set_property PACKAGE_PIN F12 [get_ports {ddr4_pl_cke[0]}]
set_property PACKAGE_PIN A15 [get_ports {ddr4_pl_odt[0]}]
set_property PACKAGE_PIN E14 [get_ports ddr4_pl_reset_n]
set_property PACKAGE_PIN J11 [get_ports {ddr4_pl_ck_t[0]}]
set_property PACKAGE_PIN J10 [get_ports {ddr4_pl_ck_c[0]}]
set_property PACKAGE_PIN G13 [get_ports sys_clk_ddr4_clk_p]
set_property PACKAGE_PIN G12 [get_ports sys_clk_ddr4_clk_n]

set_property DRIVE 8 [get_ports ddr4_pl_reset_n]
set_property SLEW MEDIUM [get_ports ddr4_pl_act_n]
set_property SLEW FAST [get_ports {ddr4_pl_dq[63]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[62]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[61]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[60]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[59]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[58]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[57]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[56]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[55]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[54]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[53]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[52]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[51]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[50]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[49]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[48]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[47]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[46]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[45]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[44]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[43]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[42]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[41]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[40]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[39]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[38]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[37]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[36]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[35]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[34]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[33]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[32]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[31]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[30]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[29]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[28]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[27]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[26]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[25]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[24]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[23]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[22]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[21]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[20]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[19]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[18]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[17]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[16]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[15]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[14]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[13]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[12]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[11]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[10]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[9]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[8]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[7]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[6]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[5]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[4]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[3]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[2]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[1]}]
set_property SLEW FAST [get_ports {ddr4_pl_dq[0]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[7]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[6]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[5]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[4]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[3]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[2]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[1]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_t[0]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[7]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[6]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[5]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[4]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[3]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[2]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[1]}]
set_property SLEW FAST [get_ports {ddr4_pl_dqs_c[0]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[63]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[62]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[61]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[60]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[59]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[58]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[57]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[56]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[55]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[54]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[53]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[52]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[51]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[50]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[49]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[48]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[47]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[46]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[45]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[44]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[43]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[42]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[41]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[40]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[39]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[38]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[37]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[36]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[35]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[34]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[33]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[32]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[31]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[30]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[29]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[28]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[27]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[26]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[25]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[24]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[23]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[22]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[21]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[20]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[19]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[18]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[17]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[16]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[15]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[14]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[13]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[12]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[11]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[10]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[9]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[8]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[7]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[6]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[5]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[4]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[3]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[2]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[1]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dq[0]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[7]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[6]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[5]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[4]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[3]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[2]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[1]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_t[0]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[7]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[6]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[5]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[4]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[3]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[2]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[1]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dqs_c[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[63]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[62]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[61]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[60]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[59]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[58]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[57]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[56]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[55]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[54]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[53]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[52]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[51]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[50]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[49]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[48]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[47]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[46]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[45]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[44]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[43]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[42]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[41]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[40]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[39]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[38]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[37]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[36]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[35]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[34]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[33]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[32]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[31]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[30]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[29]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[28]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[27]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[26]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[25]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[24]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[23]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[22]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[21]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[20]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[19]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[18]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[17]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[16]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[15]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[14]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[13]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[12]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[11]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[10]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[9]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[8]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dq[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_t[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dqs_c[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[63]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[62]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[61]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[60]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[59]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[58]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[57]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[56]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[55]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[54]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[53]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[52]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[51]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[50]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[49]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[48]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[47]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[46]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[45]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[44]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[43]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[42]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[41]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[40]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[39]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[38]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[37]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[36]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[35]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[34]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[33]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[32]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[31]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[30]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[29]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[28]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[27]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[26]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[25]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[24]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[23]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[22]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[21]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[20]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[19]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[18]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[17]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[16]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[15]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[14]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[13]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[12]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[11]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[10]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[9]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[8]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dq[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_t[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dqs_c[0]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_cs_n[0]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[7]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[6]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[5]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[4]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[3]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[2]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[1]}]
set_property ODT RTT_60 [get_ports {ddr4_pl_dm_n[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddr4_pl_dm_n[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddr4_pl_dm_n[0]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[7]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[6]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[5]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[4]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[3]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[2]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[1]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dm_n[0]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[16]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[15]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[14]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[13]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[12]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[11]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[10]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[9]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[8]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[7]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[6]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[5]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[4]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[3]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[2]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[1]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_adr[0]}]
set_property DATA_RATE SDR [get_ports ddr4_pl_act_n]
set_property DATA_RATE SDR [get_ports {ddr4_pl_ba[1]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_ba[0]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_bg[0]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_cke[0]}]
set_property DATA_RATE SDR [get_ports {ddr4_pl_odt[0]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[63]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[62]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[61]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[60]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[59]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[58]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[57]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[56]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[55]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[54]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[53]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[52]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[51]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[50]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[49]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[48]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[47]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[46]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[45]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[44]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[43]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[42]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[41]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[40]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[39]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[38]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[37]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[36]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[35]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[34]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[33]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[32]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[31]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[30]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[29]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[28]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[27]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[26]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[25]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[24]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[23]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[22]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[21]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[20]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[19]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[18]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[17]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[16]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[15]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[14]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[13]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[12]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[11]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[10]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[9]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[8]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[7]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[6]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[5]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[4]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[3]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[2]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[1]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dq[0]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[7]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[6]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[5]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[4]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[3]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[2]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[1]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_t[0]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[7]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[6]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[5]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[4]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[3]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[2]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[1]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_dqs_c[0]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_ck_t[0]}]
set_property DATA_RATE DDR [get_ports {ddr4_pl_ck_c[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[4]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[5]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[6]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_c[7]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[4]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[5]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[6]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pl_dqs_t[7]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_pl_ck_c[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_pl_ck_t[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports ddr4_pl_reset_n]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dm_n[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[9]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[16]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[17]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[18]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[19]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[20]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[21]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[22]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[23]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[24]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[25]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[26]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[27]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[28]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[29]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[30]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[31]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[32]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[33]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[34]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[35]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[36]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[37]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[38]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[39]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[40]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[41]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[42]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[43]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[44]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[45]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[46]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[47]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[48]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[49]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[50]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[51]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[52]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[53]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[54]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[55]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[56]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[57]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[58]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[59]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[60]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[61]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[62]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pl_dq[63]}]
set_property IOSTANDARD SSTL12_DCI [get_ports ddr4_pl_act_n]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[2]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[3]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[4]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[5]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[6]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[7]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[8]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[10]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[11]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[12]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[13]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[14]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[15]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_adr[16]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_ba[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_ba[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_bg[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_cs_n[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_cke[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pl_odt[0]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_cs_n[0]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[0]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[1]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[2]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[3]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[4]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[5]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[6]}]
set_property SLEW FAST [get_ports {ddr4_pl_dm_n[7]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[16]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[15]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[14]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[13]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[12]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[11]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[10]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[9]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[8]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[7]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[6]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[5]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[4]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[3]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[2]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[1]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_adr[0]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_ba[1]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_ba[0]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_bg[0]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_ck_t[0]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_ck_c[0]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_cke[0]}]
set_property SLEW MEDIUM [get_ports {ddr4_pl_odt[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports ddr4_pl_act_n]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[16]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_adr[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_ba[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_ba[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_bg[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_ck_c[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_ck_t[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_cke[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_cs_n[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dm_n[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[16]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[17]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[18]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[19]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[20]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[21]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[22]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[23]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[24]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[25]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[26]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[27]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[28]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[29]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[30]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[31]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[32]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[33]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[34]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[35]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[36]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[37]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[38]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[39]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[40]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[41]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[42]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[43]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[44]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[45]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[46]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[47]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[48]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[49]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[50]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[51]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[52]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[53]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[54]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[55]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[56]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[57]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[58]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[59]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[60]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[61]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[62]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[63]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dq[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_c[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_dqs_t[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pl_odt[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dm_n[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[8]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[9]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[10]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[11]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[12]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[13]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[14]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[15]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[16]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[17]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[18]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[19]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[20]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[21]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[22]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[23]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[24]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[25]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[26]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[27]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[28]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[29]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[30]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[31]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[32]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[33]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[34]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[35]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[36]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[37]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[38]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[39]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[40]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[41]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[42]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[43]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[44]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[45]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[46]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[47]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[48]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[49]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[50]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[51]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[52]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[53]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[54]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[55]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[56]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[57]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[58]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[59]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[60]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[61]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[62]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dq[63]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_c[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pl_dqs_t[7]}]


set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_ddr4_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_ddr4_clk_n]
create_clock -period 5.000 -name sys_clk_ddr4 [get_ports "sys_clk_ddr4_clk_p"]






# Timing
set_false_path -from [get_pins {system_bd_i/clocktreeMTS/sync_0/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}]
set_false_path -from [get_pins {system_bd_i/clocktreeMTS/sync_1/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}]
set_false_path -from [get_pins {system_bd_i/clocktreeMTS/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}]
set_false_path -from [get_pins {system_bd_i/clocktreeMTS/sync_3/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}]
set_property ASYNC_REG false [get_cells {system_bd_i/clocktreeMTS/sync_*/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]}]

set_false_path -from [get_pins {system_bd_i/adc_path/soft_reset/sync_0/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}]
set_false_path -from [get_pins {system_bd_i/adc_path/soft_reset/sync_1/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}]
set_property ASYNC_REG false [get_cells {system_bd_i/adc_path/soft_reset/sync_*/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]}]

#set_clock_groups -name asy_grp1 -asynchronous -group [get_clocks clk_pl_0] -group [get_clocks RFDAC0_CLK] -group [get_clocks RFDAC1_CLK] -group [get_clocks -of_objects [get_pins system_bd_i/clk_block/ADC_clk_wiz_*/inst/plle4_adv_inst/CLKOUT0]] 
#set_clock_groups -name asy_grp2 -asynchronous -group [get_clocks RFDAC0_CLK] -group [get_clocks RFDAC1_CLK] -group [get_clocks clk_pl_0] -group [get_clocks -of_objects [get_pins system_bd_i/clk_block/DAC_clk_wiz_*/inst/plle4_adv_inst/CLKOUT0]] 
#set_clock_groups -name asy_grp3 -asynchronous -group [get_clocks clk_pl_0] -group [get_clocks mmcm_clkout0]






# set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
# set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
# set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
# connect_debug_port dbg_hub/clk [get_nets clk]

# set_property BITSTREAM.CONFIG.UNUSEDPIN PULLDOWN[current_design]
set_property BITSTREAM.CONFIG.OVERTEMPSHUTDOWN ENABLE [current_design]
# set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

